// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	versioned "github.com/easysoft/quikon-api/client/clientset/versioned"
	internalinterfaces "github.com/easysoft/quikon-api/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/easysoft/quikon-api/client/listers/qucheng/v1beta1"
	quchengv1beta1 "github.com/easysoft/quikon-api/qucheng/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DbInformer provides access to a shared informer and lister for
// Dbs.
type DbInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.DbLister
}

type dbInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDbInformer constructs a new informer for Db type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDbInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDbInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDbInformer constructs a new informer for Db type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDbInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.QuchengV1beta1().Dbs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.QuchengV1beta1().Dbs(namespace).Watch(context.TODO(), options)
			},
		},
		&quchengv1beta1.Db{},
		resyncPeriod,
		indexers,
	)
}

func (f *dbInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDbInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *dbInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&quchengv1beta1.Db{}, f.defaultInformer)
}

func (f *dbInformer) Lister() v1beta1.DbLister {
	return v1beta1.NewDbLister(f.Informer().GetIndexer())
}
