// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	internalinterfaces "github.com/easysoft/quickon-api/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Backups returns a BackupInformer.
	Backups() BackupInformer
	// BackupSets returns a BackupSetInformer.
	BackupSets() BackupSetInformer
	// Dbs returns a DbInformer.
	Dbs() DbInformer
	// DbBackups returns a DbBackupInformer.
	DbBackups() DbBackupInformer
	// DbDumpReplicas returns a DbDumpReplicaInformer.
	DbDumpReplicas() DbDumpReplicaInformer
	// DbRestores returns a DbRestoreInformer.
	DbRestores() DbRestoreInformer
	// DbServices returns a DbServiceInformer.
	DbServices() DbServiceInformer
	// DeleteBackupRequests returns a DeleteBackupRequestInformer.
	DeleteBackupRequests() DeleteBackupRequestInformer
	// ResticRepositories returns a ResticRepositoryInformer.
	ResticRepositories() ResticRepositoryInformer
	// ResticSnapshotDumps returns a ResticSnapshotDumpInformer.
	ResticSnapshotDumps() ResticSnapshotDumpInformer
	// Restores returns a RestoreInformer.
	Restores() RestoreInformer
	// StorageProfiles returns a StorageProfileInformer.
	StorageProfiles() StorageProfileInformer
	// VolumeBackups returns a VolumeBackupInformer.
	VolumeBackups() VolumeBackupInformer
	// VolumeRestores returns a VolumeRestoreInformer.
	VolumeRestores() VolumeRestoreInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Backups returns a BackupInformer.
func (v *version) Backups() BackupInformer {
	return &backupInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// BackupSets returns a BackupSetInformer.
func (v *version) BackupSets() BackupSetInformer {
	return &backupSetInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Dbs returns a DbInformer.
func (v *version) Dbs() DbInformer {
	return &dbInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DbBackups returns a DbBackupInformer.
func (v *version) DbBackups() DbBackupInformer {
	return &dbBackupInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DbDumpReplicas returns a DbDumpReplicaInformer.
func (v *version) DbDumpReplicas() DbDumpReplicaInformer {
	return &dbDumpReplicaInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DbRestores returns a DbRestoreInformer.
func (v *version) DbRestores() DbRestoreInformer {
	return &dbRestoreInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DbServices returns a DbServiceInformer.
func (v *version) DbServices() DbServiceInformer {
	return &dbServiceInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DeleteBackupRequests returns a DeleteBackupRequestInformer.
func (v *version) DeleteBackupRequests() DeleteBackupRequestInformer {
	return &deleteBackupRequestInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ResticRepositories returns a ResticRepositoryInformer.
func (v *version) ResticRepositories() ResticRepositoryInformer {
	return &resticRepositoryInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ResticSnapshotDumps returns a ResticSnapshotDumpInformer.
func (v *version) ResticSnapshotDumps() ResticSnapshotDumpInformer {
	return &resticSnapshotDumpInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Restores returns a RestoreInformer.
func (v *version) Restores() RestoreInformer {
	return &restoreInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// StorageProfiles returns a StorageProfileInformer.
func (v *version) StorageProfiles() StorageProfileInformer {
	return &storageProfileInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VolumeBackups returns a VolumeBackupInformer.
func (v *version) VolumeBackups() VolumeBackupInformer {
	return &volumeBackupInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VolumeRestores returns a VolumeRestoreInformer.
func (v *version) VolumeRestores() VolumeRestoreInformer {
	return &volumeRestoreInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
