/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/easysoft/qucheng-operator/apis/qucheng/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeResticSnapshotDumps implements ResticSnapshotDumpInterface
type FakeResticSnapshotDumps struct {
	Fake *FakeQuchengV1beta1
	ns   string
}

var resticsnapshotdumpsResource = schema.GroupVersionResource{Group: "qucheng", Version: "v1beta1", Resource: "resticsnapshotdumps"}

var resticsnapshotdumpsKind = schema.GroupVersionKind{Group: "qucheng", Version: "v1beta1", Kind: "ResticSnapshotDump"}

// Get takes name of the resticSnapshotDump, and returns the corresponding resticSnapshotDump object, and an error if there is any.
func (c *FakeResticSnapshotDumps) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.ResticSnapshotDump, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(resticsnapshotdumpsResource, c.ns, name), &v1beta1.ResticSnapshotDump{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ResticSnapshotDump), err
}

// List takes label and field selectors, and returns the list of ResticSnapshotDumps that match those selectors.
func (c *FakeResticSnapshotDumps) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.ResticSnapshotDumpList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(resticsnapshotdumpsResource, resticsnapshotdumpsKind, c.ns, opts), &v1beta1.ResticSnapshotDumpList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.ResticSnapshotDumpList{ListMeta: obj.(*v1beta1.ResticSnapshotDumpList).ListMeta}
	for _, item := range obj.(*v1beta1.ResticSnapshotDumpList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested resticSnapshotDumps.
func (c *FakeResticSnapshotDumps) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(resticsnapshotdumpsResource, c.ns, opts))

}

// Create takes the representation of a resticSnapshotDump and creates it.  Returns the server's representation of the resticSnapshotDump, and an error, if there is any.
func (c *FakeResticSnapshotDumps) Create(ctx context.Context, resticSnapshotDump *v1beta1.ResticSnapshotDump, opts v1.CreateOptions) (result *v1beta1.ResticSnapshotDump, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(resticsnapshotdumpsResource, c.ns, resticSnapshotDump), &v1beta1.ResticSnapshotDump{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ResticSnapshotDump), err
}

// Update takes the representation of a resticSnapshotDump and updates it. Returns the server's representation of the resticSnapshotDump, and an error, if there is any.
func (c *FakeResticSnapshotDumps) Update(ctx context.Context, resticSnapshotDump *v1beta1.ResticSnapshotDump, opts v1.UpdateOptions) (result *v1beta1.ResticSnapshotDump, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(resticsnapshotdumpsResource, c.ns, resticSnapshotDump), &v1beta1.ResticSnapshotDump{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ResticSnapshotDump), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeResticSnapshotDumps) UpdateStatus(ctx context.Context, resticSnapshotDump *v1beta1.ResticSnapshotDump, opts v1.UpdateOptions) (*v1beta1.ResticSnapshotDump, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(resticsnapshotdumpsResource, "status", c.ns, resticSnapshotDump), &v1beta1.ResticSnapshotDump{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ResticSnapshotDump), err
}

// Delete takes name of the resticSnapshotDump and deletes it. Returns an error if one occurs.
func (c *FakeResticSnapshotDumps) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(resticsnapshotdumpsResource, c.ns, name), &v1beta1.ResticSnapshotDump{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeResticSnapshotDumps) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(resticsnapshotdumpsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.ResticSnapshotDumpList{})
	return err
}

// Patch applies the patch and returns the patched resticSnapshotDump.
func (c *FakeResticSnapshotDumps) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ResticSnapshotDump, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(resticsnapshotdumpsResource, c.ns, name, pt, data, subresources...), &v1beta1.ResticSnapshotDump{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ResticSnapshotDump), err
}
