// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/easysoft/quickon-api/qucheng/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBackupSets implements BackupSetInterface
type FakeBackupSets struct {
	Fake *FakeQuchengV1beta1
	ns   string
}

var backupsetsResource = schema.GroupVersionResource{Group: "qucheng", Version: "v1beta1", Resource: "backupsets"}

var backupsetsKind = schema.GroupVersionKind{Group: "qucheng", Version: "v1beta1", Kind: "BackupSet"}

// Get takes name of the backupSet, and returns the corresponding backupSet object, and an error if there is any.
func (c *FakeBackupSets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.BackupSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(backupsetsResource, c.ns, name), &v1beta1.BackupSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.BackupSet), err
}

// List takes label and field selectors, and returns the list of BackupSets that match those selectors.
func (c *FakeBackupSets) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.BackupSetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(backupsetsResource, backupsetsKind, c.ns, opts), &v1beta1.BackupSetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.BackupSetList{ListMeta: obj.(*v1beta1.BackupSetList).ListMeta}
	for _, item := range obj.(*v1beta1.BackupSetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested backupSets.
func (c *FakeBackupSets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(backupsetsResource, c.ns, opts))

}

// Create takes the representation of a backupSet and creates it.  Returns the server's representation of the backupSet, and an error, if there is any.
func (c *FakeBackupSets) Create(ctx context.Context, backupSet *v1beta1.BackupSet, opts v1.CreateOptions) (result *v1beta1.BackupSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(backupsetsResource, c.ns, backupSet), &v1beta1.BackupSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.BackupSet), err
}

// Update takes the representation of a backupSet and updates it. Returns the server's representation of the backupSet, and an error, if there is any.
func (c *FakeBackupSets) Update(ctx context.Context, backupSet *v1beta1.BackupSet, opts v1.UpdateOptions) (result *v1beta1.BackupSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(backupsetsResource, c.ns, backupSet), &v1beta1.BackupSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.BackupSet), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBackupSets) UpdateStatus(ctx context.Context, backupSet *v1beta1.BackupSet, opts v1.UpdateOptions) (*v1beta1.BackupSet, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(backupsetsResource, "status", c.ns, backupSet), &v1beta1.BackupSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.BackupSet), err
}

// Delete takes name of the backupSet and deletes it. Returns an error if one occurs.
func (c *FakeBackupSets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(backupsetsResource, c.ns, name, opts), &v1beta1.BackupSet{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBackupSets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(backupsetsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.BackupSetList{})
	return err
}

// Patch applies the patch and returns the patched backupSet.
func (c *FakeBackupSets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.BackupSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(backupsetsResource, c.ns, name, pt, data, subresources...), &v1beta1.BackupSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.BackupSet), err
}
