// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// BackupListerExpansion allows custom methods to be added to
// BackupLister.
type BackupListerExpansion interface{}

// BackupNamespaceListerExpansion allows custom methods to be added to
// BackupNamespaceLister.
type BackupNamespaceListerExpansion interface{}

// DbListerExpansion allows custom methods to be added to
// DbLister.
type DbListerExpansion interface{}

// DbNamespaceListerExpansion allows custom methods to be added to
// DbNamespaceLister.
type DbNamespaceListerExpansion interface{}

// DbBackupListerExpansion allows custom methods to be added to
// DbBackupLister.
type DbBackupListerExpansion interface{}

// DbBackupNamespaceListerExpansion allows custom methods to be added to
// DbBackupNamespaceLister.
type DbBackupNamespaceListerExpansion interface{}

// DbRestoreListerExpansion allows custom methods to be added to
// DbRestoreLister.
type DbRestoreListerExpansion interface{}

// DbRestoreNamespaceListerExpansion allows custom methods to be added to
// DbRestoreNamespaceLister.
type DbRestoreNamespaceListerExpansion interface{}

// DbServiceListerExpansion allows custom methods to be added to
// DbServiceLister.
type DbServiceListerExpansion interface{}

// DbServiceNamespaceListerExpansion allows custom methods to be added to
// DbServiceNamespaceLister.
type DbServiceNamespaceListerExpansion interface{}

// DeleteBackupRequestListerExpansion allows custom methods to be added to
// DeleteBackupRequestLister.
type DeleteBackupRequestListerExpansion interface{}

// DeleteBackupRequestNamespaceListerExpansion allows custom methods to be added to
// DeleteBackupRequestNamespaceLister.
type DeleteBackupRequestNamespaceListerExpansion interface{}

// GlobalDBListerExpansion allows custom methods to be added to
// GlobalDBLister.
type GlobalDBListerExpansion interface{}

// GlobalDBNamespaceListerExpansion allows custom methods to be added to
// GlobalDBNamespaceLister.
type GlobalDBNamespaceListerExpansion interface{}

// RestoreListerExpansion allows custom methods to be added to
// RestoreLister.
type RestoreListerExpansion interface{}

// RestoreNamespaceListerExpansion allows custom methods to be added to
// RestoreNamespaceLister.
type RestoreNamespaceListerExpansion interface{}
