/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// BackupListerExpansion allows custom methods to be added to
// BackupLister.
type BackupListerExpansion interface{}

// BackupNamespaceListerExpansion allows custom methods to be added to
// BackupNamespaceLister.
type BackupNamespaceListerExpansion interface{}

// DbListerExpansion allows custom methods to be added to
// DbLister.
type DbListerExpansion interface{}

// DbNamespaceListerExpansion allows custom methods to be added to
// DbNamespaceLister.
type DbNamespaceListerExpansion interface{}

// DbBackupListerExpansion allows custom methods to be added to
// DbBackupLister.
type DbBackupListerExpansion interface{}

// DbBackupNamespaceListerExpansion allows custom methods to be added to
// DbBackupNamespaceLister.
type DbBackupNamespaceListerExpansion interface{}

// DbDumpReplicaListerExpansion allows custom methods to be added to
// DbDumpReplicaLister.
type DbDumpReplicaListerExpansion interface{}

// DbDumpReplicaNamespaceListerExpansion allows custom methods to be added to
// DbDumpReplicaNamespaceLister.
type DbDumpReplicaNamespaceListerExpansion interface{}

// DbRestoreListerExpansion allows custom methods to be added to
// DbRestoreLister.
type DbRestoreListerExpansion interface{}

// DbRestoreNamespaceListerExpansion allows custom methods to be added to
// DbRestoreNamespaceLister.
type DbRestoreNamespaceListerExpansion interface{}

// DbServiceListerExpansion allows custom methods to be added to
// DbServiceLister.
type DbServiceListerExpansion interface{}

// DbServiceNamespaceListerExpansion allows custom methods to be added to
// DbServiceNamespaceLister.
type DbServiceNamespaceListerExpansion interface{}

// DeleteBackupRequestListerExpansion allows custom methods to be added to
// DeleteBackupRequestLister.
type DeleteBackupRequestListerExpansion interface{}

// DeleteBackupRequestNamespaceListerExpansion allows custom methods to be added to
// DeleteBackupRequestNamespaceLister.
type DeleteBackupRequestNamespaceListerExpansion interface{}

// ResticRepositoryListerExpansion allows custom methods to be added to
// ResticRepositoryLister.
type ResticRepositoryListerExpansion interface{}

// ResticRepositoryNamespaceListerExpansion allows custom methods to be added to
// ResticRepositoryNamespaceLister.
type ResticRepositoryNamespaceListerExpansion interface{}

// ResticSnapshotDumpListerExpansion allows custom methods to be added to
// ResticSnapshotDumpLister.
type ResticSnapshotDumpListerExpansion interface{}

// ResticSnapshotDumpNamespaceListerExpansion allows custom methods to be added to
// ResticSnapshotDumpNamespaceLister.
type ResticSnapshotDumpNamespaceListerExpansion interface{}

// RestoreListerExpansion allows custom methods to be added to
// RestoreLister.
type RestoreListerExpansion interface{}

// RestoreNamespaceListerExpansion allows custom methods to be added to
// RestoreNamespaceLister.
type RestoreNamespaceListerExpansion interface{}

// StorageProfileListerExpansion allows custom methods to be added to
// StorageProfileLister.
type StorageProfileListerExpansion interface{}

// StorageProfileNamespaceListerExpansion allows custom methods to be added to
// StorageProfileNamespaceLister.
type StorageProfileNamespaceListerExpansion interface{}

// VolumeBackupListerExpansion allows custom methods to be added to
// VolumeBackupLister.
type VolumeBackupListerExpansion interface{}

// VolumeBackupNamespaceListerExpansion allows custom methods to be added to
// VolumeBackupNamespaceLister.
type VolumeBackupNamespaceListerExpansion interface{}

// VolumeRestoreListerExpansion allows custom methods to be added to
// VolumeRestoreLister.
type VolumeRestoreListerExpansion interface{}

// VolumeRestoreNamespaceListerExpansion allows custom methods to be added to
// VolumeRestoreNamespaceLister.
type VolumeRestoreNamespaceListerExpansion interface{}
