// Code generated by client-gen. DO NOT EDIT.

package v1beta1

type BackupExpansion interface{}

type DbExpansion interface{}

type DbBackupExpansion interface{}

type DbRestoreExpansion interface{}

type DbServiceExpansion interface{}

type DeleteBackupRequestExpansion interface{}

type GlobalDBExpansion interface{}

type RestoreExpansion interface{}
