// Code generated by client-gen. DO NOT EDIT.

package v1beta1

type BackupExpansion interface{}

type BackupSetExpansion interface{}

type DbExpansion interface{}

type DbBackupExpansion interface{}

type DbDumpReplicaExpansion interface{}

type DbRestoreExpansion interface{}

type DbServiceExpansion interface{}

type DeleteBackupRequestExpansion interface{}

type ResticRepositoryExpansion interface{}

type ResticSnapshotDumpExpansion interface{}

type RestoreExpansion interface{}

type StorageProfileExpansion interface{}

type VolumeBackupExpansion interface{}

type VolumeRestoreExpansion interface{}
