// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	scheme "github.com/easysoft/quickon-api/client/clientset/versioned/scheme"
	v1beta1 "github.com/easysoft/quickon-api/qucheng/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RestoreSetsGetter has a method to return a RestoreSetInterface.
// A group's client should implement this interface.
type RestoreSetsGetter interface {
	RestoreSets(namespace string) RestoreSetInterface
}

// RestoreSetInterface has methods to work with RestoreSet resources.
type RestoreSetInterface interface {
	Create(ctx context.Context, restoreSet *v1beta1.RestoreSet, opts v1.CreateOptions) (*v1beta1.RestoreSet, error)
	Update(ctx context.Context, restoreSet *v1beta1.RestoreSet, opts v1.UpdateOptions) (*v1beta1.RestoreSet, error)
	UpdateStatus(ctx context.Context, restoreSet *v1beta1.RestoreSet, opts v1.UpdateOptions) (*v1beta1.RestoreSet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.RestoreSet, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.RestoreSetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.RestoreSet, err error)
	RestoreSetExpansion
}

// restoreSets implements RestoreSetInterface
type restoreSets struct {
	client rest.Interface
	ns     string
}

// newRestoreSets returns a RestoreSets
func newRestoreSets(c *QuchengV1beta1Client, namespace string) *restoreSets {
	return &restoreSets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the restoreSet, and returns the corresponding restoreSet object, and an error if there is any.
func (c *restoreSets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.RestoreSet, err error) {
	result = &v1beta1.RestoreSet{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("restoresets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RestoreSets that match those selectors.
func (c *restoreSets) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.RestoreSetList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.RestoreSetList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("restoresets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested restoreSets.
func (c *restoreSets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("restoresets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a restoreSet and creates it.  Returns the server's representation of the restoreSet, and an error, if there is any.
func (c *restoreSets) Create(ctx context.Context, restoreSet *v1beta1.RestoreSet, opts v1.CreateOptions) (result *v1beta1.RestoreSet, err error) {
	result = &v1beta1.RestoreSet{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("restoresets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(restoreSet).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a restoreSet and updates it. Returns the server's representation of the restoreSet, and an error, if there is any.
func (c *restoreSets) Update(ctx context.Context, restoreSet *v1beta1.RestoreSet, opts v1.UpdateOptions) (result *v1beta1.RestoreSet, err error) {
	result = &v1beta1.RestoreSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("restoresets").
		Name(restoreSet.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(restoreSet).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *restoreSets) UpdateStatus(ctx context.Context, restoreSet *v1beta1.RestoreSet, opts v1.UpdateOptions) (result *v1beta1.RestoreSet, err error) {
	result = &v1beta1.RestoreSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("restoresets").
		Name(restoreSet.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(restoreSet).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the restoreSet and deletes it. Returns an error if one occurs.
func (c *restoreSets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("restoresets").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *restoreSets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("restoresets").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched restoreSet.
func (c *restoreSets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.RestoreSet, err error) {
	result = &v1beta1.RestoreSet{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("restoresets").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
